sonar.host.url=https://sonar.hirusha.xyz

sonar.projectKey=hirusha-realworld-api
sonar.projectName=Hirusha RealWorld API Jenkins HD
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,reports/**

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/api/lcov.info
